program → (declaration)* EOF ;

declaration → varDecl | statement ;

varDecl → "var" IDENTIFIER ("=" expression)? ";" ;

statement → block | exprstatement | printstatement ;

block → "{" declaration "}";

exprstatement → expression ";" ;

printstatement → "print" expression ";" ;

expression → assignment ;

assignment → IDENTIFIER "=" assignment | equality ;

equality       → equality ("==" | "!=") comparison | comparison ;

equality → comparison (("==" | "!=") comparison)* ;

comparison → term (( ">" | ">=" | "<" | "<=" ) term)* ;

term → factor (("-" | "+") factor)* ;

factor → unary (("*" | "/") unary)* ;

primary        → "true" | "false" | "nil" | NUMBER | STRING | "(" expression ")" | IDENTIFIER ;
