program → (declaration)* EOF ;

declaration → varDecl | statement ;

varDecl → "var" IDENTIFIER ("=" expression)? ";" ;

statement → functionstatement | returnstatement | forstatement | whilestatement | ifstatement | block | exprstatement | printstatement ;

functionstatement → "fun" IDENTIFIER "(" parameters? ")" block ;

parameters → IDENTIFIER ( "," IDENTIFIER )* ;

returnstatement → "return" expression? ";" ;

forstatement → "for" "(" ( varDecl | exprstatement | ";" ) expression? ";" expression? ")" statement ;

whilestatement → "while" "(" expression ")" statement ;

ifstatement → "if" "(" expression ")" statement ("else" statement)? ;

block → "{" declaration* "}" ;

exprstatement → expression ";" ;

printstatement → "print" expression ";" ;

expression → assignment ;

assignment → IDENTIFIER "=" assignment | logical_or ;

logical_or → logical_and ( "or" logical_and )* ;

logical_and → equality ( "and" equality )* ;

equality → comparison (("==" | "!=") comparison)* ;

comparison → term (( ">" | ">=" | "<" | "<=" ) term)* ;

term → factor (("-" | "+") factor)* ;

factor → unary (("*" | "/") unary)* ;

unary → ("!" | "-") unary | call ;

call → primary ( "(" arguments? ")" )* ;

arguments → expression ( "," expression)* ;

primary → "true" | "false" | "nil" | NUMBER | STRING | "(" expression ")" | IDENTIFIER ;
